<ol class="inline">
<?php foreach ($this->tags as $tag): ?>
    <li><a  class="Tag"
            about="<?php echo $tag['uri'] ?>"
            href="<?php echo $tag['link'] ?>"
           ><?php echo $tag['title'] ?></a></li>
<?php endforeach; ?>
</ol>

<?php if (!empty($this->message)): ?>
    <?php if (!empty($this->messagetype)): ?>
        <span class="messagebox <?php echo $this->messagetype ?>"><?php echo ($this->message) ?></span>
    <?php else: ?>
        <span class="messagebox info"><?php echo ($this->message) ?></span>
    <?php endif ?>
<?php endif ?>
